Update dbt.yml

diff --git a/.github/workflows/dbt.yml b/.github/workflows/dbt.yml
--- a/.github/workflows/dbt.yml
+++ b/.github/workflows/dbt.yml
@@ -45,8 +45,23 @@ jobs:
 
     - name: Copy profiles.yml, dbt_project.yml, and .dbt.yml
       run: |
-        cp dbt_demo/demohub/profiles.yml $HOME/.dbt/
-        cp dbt_demo/demohub/dbt_project.yml dbt_demo/demohub/.dbt.yml $HOME/.dbt/
+        if [ -e "dbt_demo/demohub/profiles.yml" ]; then
+          echo "Copying profiles.yml to $HOME/.dbt/"
+          cp dbt_demo/demohub/profiles.yml $HOME/.dbt/
+        else
+          echo "Error: profiles.yml not found in dbt_demo/demohub/ directory."
+          ls -R dbt_demo/demohub  # Print directory contents for debugging
+          exit 1  # Exit the workflow with an error code if the file doesn't exist
+        fi
+
+        if [ -e "dbt_demo/demohub/dbt_project.yml" ]; then
+          echo "Copying dbt_project.yml to $HOME/.dbt/"
+          cp dbt_demo/demohub/dbt_project.yml dbt_demo/demohub/.dbt.yml $HOME/.dbt/
+        else
+          echo "Error: dbt_project.yml not found in dbt_demo/demohub/ directory."
+          ls -R dbt_demo/demohub  # Print directory contents for debugging
+          exit 1  # Exit the workflow with an error code if the file doesn't exist
+        fi
 
     - name: Print contents of $HOME/.dbt/
       run: |
@@ -68,7 +83,6 @@ jobs:
           ls -R $HOME/.dbt/  # Print contents of $HOME/.dbt/ for debugging
           exit 1  # Exit the workflow with an error code if the file doesn't exist
         fi
-
 
     - name: dbt debug
       run: dbt debug --profiles-dir $HOME/.dbt/
